# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(
	build_numeber: app_store_build_number + 1,
	workspace: "iOS-txtreader.xcworkspace"
    )
    sync_code_signing(type: "appstore")
    build_app(workspace: "iOS-txtreader.xcworkspace", scheme: "iOS-txtreader")
    upload_to_app_store
  end
end
